package test_only;

public class for_test {
	 static int getNewNumber(int num1) {
		//this method is aim to get the next integer generated by numerologist.
		int out = 0;
		int temp;
		while (num1 != 0) {
			temp = num1%10;
			out += temp;
			num1 = num1 / 10;
		}
		
		return out;
	}
	
	
	public static void main(String[] args) {
		//System.out.println(987/10);
		System.out.println(getNewNumber(987));
		
	}

}